### ISSUE TITLE
TODO Features

### ISSUE THREAD

**Issue by aciidgh** [aciidb0mb3r/BananaBot#1]
- [ ] Support snapshots command
- [ ] Autopost on new snapshot releases
- [ ] Fetch stats for llbuild repo `stats (llbuild|swiftpm)`
- [ ] search for a swift package `search package <name>`
- [ ] show a random swift package `random package`
